baseURL = 'https://ai-co-blog-arealclimber.vercel.app/'
languageCode = 'zh-tw'
title = 'AI co-blog'
theme = "PaperMod"
paginate = 5

[params]
  authors = ["Daniel", "Shirley", "Wally", "Winnie", "瑜楓"]




